db_name = "all_streams_unique_v3"  # Will be used to name db file
data_path = "data/" # relative path to JSON files
felis_path = "schema.yaml" # relative path to felis schema YAML file
lookup_tables = [
    "Publications",
    "Telescopes",
    "Instruments",
    "PhotometryFilters",
    "RegimeList",
    "AssociationList",
    "ParameterList"
    ]
