# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Astro Web

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
permissions:
  contents: read

jobs:  
  test:
    runs-on: ubuntu-latest
    env:
      ASTRO_WEB_DATABASE_URL: "sqlite:///SIMPLE.sqlite"
      ASTRO_WEB_LOOKUP_TABLES: "Publications,Telescopes,Instruments,PhotometryFilters,Versions,RegimeList,SourceTypeList,ParameterList,AssociationList,CompanionList,Modes,Filters,Citations,References,Parameters,Regimes"
      ASTRO_WEB_PRIMARY_TABLE: "Sources"
      ASTRO_WEB_SOURCE_COLUMN: "source"
      ASTRO_WEB_FOREIGN_KEY: "source"
      ASTRO_WEB_RA_COLUMN: "ra"
      ASTRO_WEB_DEC_COLUMN: "dec"
      ASTRO_WEB_SPECTRA_URL_COLUMN: "access_url"
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        uv sync --all-extras --dev

    - name: Download database
      run: |
        curl -L https://github.com/SIMPLE-AstroDB/SIMPLE-binary/raw/main/SIMPLE.sqlite -o SIMPLE.sqlite

    - name: Run linter
      run: |
        uv run ruff check .

    - name: Test with pytest
      run: |
        uv run pytest --cov --cov-branch --cov-report=xml
